env.projectname = env.JOB_NAME.split('/')[0]
env.formatbranchname = env.BRANCH_NAME.replace('/','SLASH')
env.jenkinsBranchName = env.BRANCH_NAME.replace('/','%2F')


pipeline {
    agent any
    
    triggers {
        gitlab(triggerOnPush: true, branchFilterType: 'All')
    }

    options { 
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '5'))
        gitLabConnection('gitlab-ci')
    }
    
    stages {
        stage('clean') {
            steps {
                sh 'echo $JAVA_HOME'
                sh '/opt/apache-maven-3.6.0/bin/mvn clean'
            }
        }
        
        stage('compile') {
            steps {
                sh 'echo $JAVA_HOME'
                sh '/opt/apache-maven-3.6.0/bin/mvn -Dmaven.test.skip=true compile'
            }
        }

        stage('test') {
            steps {
                sh 'echo $JAVA_HOME'
                sh 'echo `pwd`'
                sh '/opt/apache-maven-3.6.0/bin/mvn test'
            }
        }

        stage('package') {
            steps {
                sh 'echo $JAVA_HOME'
                sh 'echo `pwd`'
                sh '/opt/apache-maven-3.6.0/bin/mvn clean package'
            }
        }

        stage('Distribution') {
            steps {
                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'mkdir -p /root/app/'"
                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/smart-learning-data*/ && sh stop.sh'"
                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/ && rm -rf smart-learning-data*'"
                sh "sshpass -p123456 scp -o StrictHostKeyChecking=no smart-learning-data/target/*.zip root@10.100.1.213:/root/app/"
                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/ && unzip *.zip && rm -rf *.zip'"

                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/smart-learning-workflow*/ && sh stop.sh'"
                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/ && rm -rf smart-learning-workflow*'"
                sh "sshpass -p123456 scp -o StrictHostKeyChecking=no smart-learning-workflow/target/*.zip root@10.100.1.213:/root/app/"
                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/ && unzip *.zip && rm -rf *.zip'"

                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/smart-learning-data* && sh start.sh'"
                sh "sshpass -p123456 ssh -o StrictHostKeyChecking=no root@10.100.1.213 'cd /root/app/smart-learning-workflow* && sh start.sh'"
            }
        }
    }

    post {

        success {

            mail bcc: '',
                body: """
                \nSUCCESS\n
BranchName: ${env.BRANCH_NAME}\n
Jenkins Details: ${env.JENKINS_URL}blue/organizations/jenkins/${env.projectname}/detail/${env.jenkinsBranchName}/${env.BUILD_NUMBER}/pipeline \n\n
                    """,
                from: 'tdj@bsfit.com.cn',
                replyTo: '',
                subject: "CI SUCCESS on smartLearning-data/workflow-${env.BRANCH_NAME}-${env.BUILD_NUMBER}",
                to: 'tdj@bsfit.com.cn'

        }

        failure {

            mail bcc: '',
                body: """
                \nFAILURE\n
BranchName: ${env.BRANCH_NAME}\n
Jenkins Details: ${env.JENKINS_URL}blue/organizations/jenkins/${env.projectname}/detail/${env.jenkinsBranchName}/${env.BUILD_NUMBER}/pipeline \n\n
                    """,
                from: 'tdj@bsfit.com.cn',
                replyTo: '',
                subject: "CI FAILURE on smartLearning-data/workflow-${env.BRANCH_NAME}-${env.BUILD_NUMBER}",
                to: 'tdj@bsfit.com.cn'
        }

        always {
            sh 'echo good job'
            archive 'smart-learning-data/target/*.zip'
            archive 'smart-learning-data/target/smart-learning-data-*.jar'
            archive 'smart-learning-workflow/target/*.zip'
            archive 'smart-learning-workflow/target/smart-learning-workflow-*.jar'
            step([$class:'JacocoPublisher'])
        }
        
    }

}
